(* Template for a WP Coq proof obligation.

   File location:  <session>/interactive/<goal>.v
   Generate with:  frama-c ... -wp-prover coq -wp-interactive update -wp-session <session>
   Iterate with:   scripts/coq-iter.sh <session>/interactive/<goal>.v
   Confirm with:   frama-c ... -wp-prover coq -wp-interactive batch -wp-session <session>

   ONLY the Proof. ... Qed. block below is yours. Everything above it is regenerated by
   -wp-interactive update and any edit there is destroyed -- including Require Import,
   which is why the imports live inside the proof. *)

(* ... generated preamble: BuiltIn, memory model, your L_/P_/Q_ definitions ... *)

(* Why3 goal *)
Theorem wp_goal :
  forall (t:addr -> Numbers.BinNums.Z) (a:addr) (n:Numbers.BinNums.Z),
  is_sint32_chunk t -> (0 <= n)%Z ->
  (0 <= (L_Example t a n))%Z.
(* Why3 intros t a n h1 h2. *)   (* raw names; rename them below for readability *)
Proof.
  Require Import Psatz.          (* lia *)
  Require Import ZArith.

  (* Name hypotheses after the ACSL variables and labels. The is_sint32* hypotheses are
     almost always needed by lia later, so intro them explicitly. *)
  intros L a n L32 nNN.

  (* Induction over a non-negative integer: base case, then step. *)
  apply natlike_rec2 with (z := n); auto with zarith.
  - (* base: n = 0.  Rewrite with the ACSL lemma you already proved: Q_<lemma name>. *)
    rewrite Q_Example_Empty; auto with zarith.
  - (* step *)
    intros z Hz IHz.
    replace (Z.succ z) with (1 + z)%Z by lia.
    rewrite <- Q_Example_Next by lia.
    (* Coq prints -1 as `- (1)`. `replace (-1 + ...)` silently fails to match. *)
    replace (- (1) + (1 + z))%Z with z by lia.
    (* Stuck? Insert `Show.` here to print the goal state, then re-run coq-iter.sh. *)
    lia.
Qed.

(* If this proof is getting long, stop: add another ACSL lemma and prove that separately.
   A long Coq proof usually means a missing intermediate lemma.
   And check first whether a lemma function (frama-c-wp/references/auto-active.md) proves it automatically. *)
